server:
  port:
    8082
spring:
  datasource:
    url: jdbc:h2:mem:dc
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect